#ifndef TIME_TRACKER_CONFIG_H
#define TIME_TRACKER_CONFIG_H

#include <windows.h>

#define MAX_STR 255
#define HID_REPORT_TOTAL_LEN 65
#define HID_REPORT_PAYLOAD_LEN 64
#define HID_REPORT_ID_WINDOW 0x01
#define HID_REPORT_ID_COMMAND 0x02
#define HID_REPORT_ID_ORDER 0x03
#define HID_REPORT_ID_WINDOW_CHUNK_START 0x05
#define HID_REPORT_ID_WINDOW_CHUNK_DATA 0x06
#define HID_REPORT_ID_WINDOW_CHUNK_END 0x07
#define HID_REPORT_WINDOW_CHUNK_BYTES (HID_REPORT_PAYLOAD_LEN - 1)
#define WINDOW_POLL_MS_DEFAULT 500
#define WINDOW_POLL_MS_MIN 50
#define AGENT_POLL_IDLE_LOG_EVERY 20
#define AGENT_POLL_DUP_LOG_EVERY 20
#define AGENT_POLL_RAW_PREVIEW 12
#define LOG_PATH_MAX (MAX_PATH * 2)
#define ORDER_QUEUE_CAPACITY 32
#define ORDER_MAX_LEN HID_REPORT_PAYLOAD_LEN

#define HID_TEENSY_VENDOR_ID 0x16C0
#define HID_ANY_PRODUCT_ID 0x0000
#define HID_FEATURE_INTERFACE_NUMBER 2

#endif
